/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2_abdenagolopez;

import javax.swing.JOptionPane;

/**
 *
 * @author Abdenago
 */
public class Encuesta extends javax.swing.JFrame {

        
    
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tcorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tencuesta = new javax.swing.JLabel();
        bregistrar = new javax.swing.JButton();
        bencuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre y apellido");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(76, 70, 130, 16);
        getContentPane().add(tnombre);
        tnombre.setBounds(220, 70, 157, 22);

        jLabel2.setText("Edad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(76, 114, 110, 16);
        getContentPane().add(tedad);
        tedad.setBounds(220, 110, 157, 22);

        jLabel3.setText("Correo electronico");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(76, 154, 130, 16);
        getContentPane().add(tcorreo);
        tcorreo.setBounds(220, 150, 157, 22);

        jLabel4.setText("Carro propio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(76, 191, 120, 16);

        buttonGroup1.add(rb1);
        rb1.setText("Si");
        getContentPane().add(rb1);
        rb1.setBounds(220, 190, 60, 21);

        buttonGroup1.add(rb2);
        rb2.setText("No");
        getContentPane().add(rb2);
        rb2.setBounds(290, 190, 70, 21);

        jLabel5.setText("Numero de encuesta ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 17, 130, 16);

        tencuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tencuesta.setText("0");
        tencuesta.setToolTipText("");
        tencuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tencuesta);
        tencuesta.setBounds(130, 10, 30, 20);

        bregistrar.setText("Registrar encuesta");
        bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bregistrar);
        bregistrar.setBounds(50, 240, 180, 23);

        bencuesta.setText("Reporte de encuentas");
        bencuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bencuestaActionPerformed(evt);
            }
        });
        getContentPane().add(bencuesta);
        bencuesta.setBounds(230, 240, 210, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrarActionPerformed
        
        tencuesta.setText(tencuesta.getText() + "1");
        
        String carrop;
        carrop = "";    
        
        
        /*if (tedad > 50 || tedad <18) {
            
             JOptionPane.showMessageDialog(null,"Debe tener una edad entre 18 y 50 años ");
             
        } else {*/
            
        if (rb1.isSelected()) {
           carrop = "Si"; 
        } else if (rb2.isSelected()) {
           carrop = "No"; 
        }
        
        ClsEncuesta.setNombre(tnombre.getText());
         ClsEncuesta.setCorreo(tcorreo.getText());
         ClsEncuesta.setCarro(String.valueOf(carrop));
         ClsEncuesta.setEdad(Float.parseFloat(tedad.getText()));
           
           tnombre.setText("");
           tcorreo.setText("");
           tedad.setText("");
           
    
    }//GEN-LAST:event_bregistrarActionPerformed

    private void bencuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bencuestaActionPerformed
        
        ClsEncuesta encuesta = new ClsEncuesta();
        
        encuesta.imprimir();
        
            
        
       /*Registro Registro = new Registro();
       Registro.setSize(800,600);
       Registro.setVisible(true);
       this.hide();*/
       
    }//GEN-LAST:event_bencuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bencuesta;
    private javax.swing.JButton bregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tcorreo;
    private javax.swing.JTextField tedad;
    private javax.swing.JLabel tencuesta;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
